version: '3'
services:
  frontend:
    image: client
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
