version: '3'
services:
  frontend_dev:
    # stdin_open: true
    # tty: true
    image: client-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
